blank_issues_enabled: false
contact_links:
  - name: Rclone Forum
    url: https://forum.rclone.org/
    about: For questions around rclone itself.
  - name: Rclone Issue Tracker
    url: https://github.com/rclone/rclone/issues
    about: When you are sure rclone does not work correctly.