name: Android CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches-ignore:
      - 'master'

jobs:
  build-all:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: gradle/wrapper-validation-action@v1
    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: 20
        distribution: "temurin"
        cache: 'gradle'
    - name: Set up Go 1.20
      uses: actions/setup-go@v4
      with:
        go-version: stable
        check-latest: true

    - name: Build rclone
      run: ./gradlew rclone:buildArm64
    - name: Build app
      run: ./gradlew assembleOssArm64Release

    - name: Sign release
      uses: ilharp/sign-android-release@v1
      id: sign_app
      with:
        releaseDir: app/build/outputs/apk/ossArm64/release
        signingKey: ${{ secrets.SIGNING_KEY }}
        keyAlias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}

    - name: Upload APK (arm64)
      uses: actions/upload-artifact@v3
      with:
        name: arm64.apk
        path: ${{steps.sign_app.outputs.signedFile}}
