name: Android CI

on:
  push:
    branches:
      - 'gradle'
  pull_request:
    branches-ignore:
      - 'dev'

jobs:
  build-all:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: gradle/wrapper-validation-action@v1
    - name: Gradle
      run: |
        ./gradlew wrapper --gradle-version 8.2.1
        git config --global user.email "kgstradviolin@outlook.com"
        git config --global user.name "Kostas Giapis"
        git add .
        git commit -m k
        git push https://tsiflimagas:${ACCESS_TOKEN}@github.com/tsiflimagas/extRact.git
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
